version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook
    volumes:
      - ..:/home/jovyan/code
    ports:
      - "8888:8888"
    command: start.sh jupyter notebook --NotebookApp.token='' --NotebookApp.disable_check_xsrf=true --NotebookApp.allow_origin='*' --NotebookApp.ip='0.0.0.0'
